sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/gitberg.git
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+git://github.com/rdhyee/pg-epubmaker.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: q26PqdL+FHnSKG7rfwhAQa9AXmTMcQlMK8/OUQIJ0XGo3Uh3ZbwBthzgGoMJUkQFn3DLeiGMj0mL+YYac39jM/IGuMzwTdfMIoX+yXVvg2uO6OnreI9wMgWZVqgB81P5/zRaGxtGkby1oJtoe6SU8qfuCAJIm6gDdtHK4rTO1YzOLkadsupKCUnj+0Um4ErIwug498quB9Fp0oY0KwYG6eKVgJlJRwPX7yXFM1hAchAFYa9bDRlQHoneUKqNaRjppGXnVjDgavYz44p8kLCkM6Z48POATYg1wEhgxhtCEy4qwqvgZV9uk0maVRml5bLWmfVzvheaXL9TsVB1Z7OmsKnwmumXgp+n21V8Z9EptaYAiQxyjc/D4+OVvb9qjQKZ86shg9abABJjz+7yNN5xHW1LQWleBqdUBrY2jQrPyNK2TP962FqCW2lRYRrHGXF71L6YGPFg6F83S8aXj6Zjh7IkWRNHIR7VovqhBzmQu+xDgSiQ+7H98w3mCiqtfFogzk+E+CevvGoPyuh0Z96AuFXXNSaPv253LtV30UEUeD8yus3Bb1LYr5dSuZdnHaOlJJmu179/PrYo38GEfw8JclqGnnTZr1S2kxXOw+/JInSaBNxrQUUkj2YrgznN0uPjz3cVO2IGYA9xIDf1ZojvSWxat/qO2herp10GzHz2dfo=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: rdhyee/Tarzan-of-the-Apes_78
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy